version: "1"
services:
  nest:
    image: choseongwoo/ganoverflow-back:v0531-1-initdb
    container_name: nest
    #volumes:
    #  - ./src:/app/src
    #  - .env:/app/.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db
  nginx:
    container_name: nginx-nest
    image: nginx:1.19.0-alpine
    depends_on:
      - nest
    ports:
      - "3001:3001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  db:
    image: postgres:13
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: modulers
      POSTGRES_PASSWORD: inssafood
      POSTGRES_DB: ganoverflow
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
