name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set image name with date
        run: echo "IMAGE_NAME=ganoverflow:$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: cd nest && docker build -t ${{ env.IMAGE_NAME }} . && cd ../

      # - name: Modify docker-compose.yml
      #   run: |

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 118.67.134.211
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ganoverflow
            docker-compose down
            images=$(docker images | awk 'NR>4 {print $3}')
            if [ -n "$images" ]; then
              echo "$images" | xargs docker rmi -f
            fi
            sed -i "s|image: \${here}|image: ${{ env.IMAGE_NAME }}|" docker-compose.yml
            docker-compose up --build -d
